### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by jordanmkoncz** [danielwelch/django-q-sentry#1]
Hi there,

I'm trying to follow the Installation instructions in the README, but I'm getting an error. Below is the output from `pip install django-q[sentry]`

```
(venv) Jordans-15-MBP:my_project jordan$ pip install django-q[sentry]
Requirement already satisfied: django-q[sentry] in ./venv/lib/python3.5/site-packages
Requirement already satisfied: arrow in ./venv/lib/python3.5/site-packages (from django-q[sentry])
Requirement already satisfied: django-picklefield in ./venv/lib/python3.5/site-packages (from django-q[sentry])
Requirement already satisfied: blessed in ./venv/lib/python3.5/site-packages (from django-q[sentry])
Requirement already satisfied: django>=1.8 in ./venv/lib/python3.5/site-packages (from django-q[sentry])
Collecting django-q-sentry>=0.1; extra == "sentry" (from django-q[sentry])
  Could not find a version that satisfies the requirement django-q-sentry>=0.1; extra == "sentry" (from django-q[sentry]) (from versions: )
No matching distribution found for django-q-sentry>=0.1; extra == "sentry" (from django-q[sentry])
```

I actually can't seem to find `django-q-sentry` on https://pypi.python.org so I'm thinking the issue might be that the package hasn't been published to PyPI yet? Any suggestions?

**Comment by jordanmkoncz** [comment]
For anyone else who's having this problem, a workaround is to install `django-q-sentry` manually by adding `
git+https://github.com/danielwelch/django-q-sentry.git@c492988339491eaa3beb3cf33dbab6f3443ad6d3#egg=django_q_sentry` to my `requirements.txt`.

**Comment by danielwelch** [comment]
Terrible oversight by me, sorry. Just published to PyPI.

**Comment by jordanmkoncz** [comment]
No worries, thanks for your great work on adding Sentry integration for `django-q` @danielwelch.

It looks like there's another minor problem with the integration, I created an issue for it here: https://github.com/Koed00/django-q/issues/276. Could you please take a look? :)
